version: "3.9"

services:
  app:
    build:
      context: "./app"
    env_file: .env
    volumes:
      - ./app/:/usr/app/
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "5000:5000"
  database:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 10s
      interval: 5s
      timeout: 15s
      retries: 5
